Package names, changelog and migration guide
RedMadRobot/debug-panel-android pull request #18
Opened 2024-07-19 07:41 UTC by EmogurovAnton

2024-07-19 10:41 UTC, AleksandrTabolin commented on README.md
> +**[Changelog][changelog]** | **[Документация по разработке плагинов][plugin-development-doc]** | **[Миграция не новые версии][migration-guide]**
[Миграция на новые версии] ?

2024-07-19 13:45 UTC, AleksandrTabolin commented on plugins/variable/src/main/kotlin/com/redmadrobot/debug/plugin/variable/ui/VariableViewModel.kt
> +    private val repository: com.redmadrobot.debug.plugin.variable.data.VariableRepository,
в import

2024-07-19 14:13 UTC, osipxd requested changes

2024-07-19 14:13 UTC, osipxd commented on docs/migration_guide.md
> +`accounts-plugin` -> `plugin-accounts`
Тут и в остальных случаях
```suggestion
`com.redmadrobot.debug:accounts-plugin` -> `com.redmadrobot.debug:plugin-accounts`
```
Или можно использовать тоже diff
```diff
- debugImplementation("com.redmadrobot.debug:accounts-plugin:<version>")
+ debugImplementation("com.redmadrobot.debug:plugin-accounts:<version>")
```

2024-07-19 14:13 UTC, osipxd commented on docs/migration_guide.md
> +> Для оботражения необходимо вызвать метод `showPanel` у объекта `DebugPanel`
Галочки `>` тут лишние перед всеми строками в разделе.

Можно упростить, написать что-то типа такого:
```
Вместо метода `DebugPanel.showPanel(FragmentManager)` следует использовать `DebugPanel.showPanel(Activity)`
```

2024-07-19 14:13 UTC, osipxd commented on docs/changelog.md
> +* Breaking changes - Изменены наименования пакетов во всех модулях. Приведены к общему виду.
Стоит дать ссылку на док с миграцией

2024-07-19 14:47 UTC, EmogurovAnton commented on docs/migration_guide.md
> ++ import com.redmadrobot.debug.core.internal.DebugPanel
Да, метод инициализации и отображения `showPanel` лежат в этом объекте

2024-07-19 14:52 UTC, EmogurovAnton commented on docs/migration_guide.md
> ++ import com.redmadrobot.debug.core.internal.DebugPanel
Это как раз написано в [разделе](https://github.com/RedMadRobot/debug-panel-android?tab=readme-ov-file#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8-%D0%B2-%D0%BA%D0%BE%D0%B4%D0%B5:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%B1%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B8%20%D0%B2%20%D0%BA%D0%BE%D0%B4%D0%B5) "Использование библиотеки в коде"

2024-07-22 12:40 UTC, osipxd commented on core/src/main/kotlin/com/redmadrobot/debug/core/DebugPanel.kt
> +import com.redmadrobot.debug.core.internal.DebugEvent
DebugEvent тоже часть публичного API, стоит его вынести из internal на уровень выше.
Кстати, a `PluginDpendencyContainer` и `CommonContainer` это как раз внутренние штуки, которые должны быть в internal.

2024-07-22 12:40 UTC, osipxd commented on docs/changelog.md
> +* [Breaking changes][migration-guide] - Изменены наименования пакетов во всех модулях. Приведены к общему виду.
```suggestion
* **Breaking changes:** Изменены Maven-координаты библиотек. Наименования пакетов во всех модулях приведены к общему виду. См. [гайд по миграции][migration-guide].
```

2024-07-22 12:40 UTC, osipxd commented on docs/migration_guide.md
> +### Изменения Maven-координатов библиотек
В прошлую итерацию тоже оставлял коммент, что этот блок стоит перенести в самый верх, так как это самое важное изменение. Если его не сделать, не получится другие шаги миграции выполнить.

2024-07-22 13:23 UTC, AleksandrTabolin approved these changes

2024-07-22 13:52 UTC, osipxd commented on core/src/main/kotlin/com/redmadrobot/debug/core/DebugEvent.kt
> +@OptIn(DebugPanelInternal::class)
А для чего тут OptIn?

2024-07-22 14:05 UTC, EmogurovAnton commented on core/src/main/kotlin/com/redmadrobot/debug/core/DebugEvent.kt
> +@OptIn(DebugPanelInternal::class)
@osipxd, поправил

2024-07-22 14:11 UTC, osipxd commented on docs/migration_guide.md
> ++ import com.redmadrobot.debug.core.internal.DebugPanel
```suggestion
+ import com.redmadrobot.debug.core.DebugPanel
```

2024-07-22 14:13 UTC, osipxd commented on core/src/main/kotlin/com/redmadrobot/debug/core/DebugEvent.kt
> +import com.redmadrobot.debug.core.annotation.DebugPanelInternal
Можно удалить?

2024-07-22 14:25 UTC, osipxd approved these changes

2024-07-22 14:32 UTC, merged