Fix crash on Android 14 and target SDK 34
RedMadRobot/debug-panel-android pull request #7
Opened 2023-09-08 12:46 UTC by antonchik-a

2023-09-08 13:03 UTC, osipxd requested changes

2023-09-08 13:03 UTC, osipxd commented on buildSrc/src/main/kotlin/Project.kt
> +    const val COMPILE_SDK = 33
I think compileSdk should also be 34

2023-09-08 18:08 UTC, osipxd approved these changes

2023-09-11 06:51 UTC, Zestxx approved these changes

2023-09-11 07:20 UTC, merged